// AUTO-GENERATED by scripts/build-brand.mjs — do not edit by hand.
export const logoData = {
  "full": {
    "ink": "brand/logo-ink.svg",
    "width": 1510,
    "height": 560,
    "paperWidth": 1400,
    "paper": [
      {
        "file": "kraft-strip-640.webp",
        "w": 640
      },
      {
        "file": "kraft-strip-1000.webp",
        "w": 1000
      },
      {
        "file": "kraft-strip-1400.webp",
        "w": 1400
      }
    ]
  },
  "compact": {
    "ink": "brand/logo-compact-ink.svg",
    "width": 830,
    "height": 300,
    "paperWidth": 760,
    "paper": [
      {
        "file": "kraft-strip-compact-320.webp",
        "w": 320
      },
      {
        "file": "kraft-strip-compact-480.webp",
        "w": 480
      },
      {
        "file": "kraft-strip-compact-760.webp",
        "w": 760
      }
    ]
  }
} as const
