/**
 * Builds optimized, responsive images from the originals in assets/.
 *
 *   npm run images
 *
 * Reads scripts/images.config.mjs, writes AVIF + WebP files at several widths
 * to public/images/, and regenerates src/data/images.generated.ts (sizes,
 * srcsets and a tiny blurred placeholder for each photo).
 */
import { createHash } from 'node:crypto'
import { mkdir, readdir, rm, writeFile, readFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'
import config from './images.config.mjs'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const outDir = path.join(root, 'public/images')
const manifestPath = path.join(root, 'src/data/images.generated.ts')

const AVIF = { quality: 58, effort: 6 }
const WEBP = { quality: 80, effort: 6 }

await mkdir(outDir, { recursive: true })
for (const file of await readdir(outDir)) {
  if (/\.(avif|webp|jpe?g|png)$/.test(file)) await rm(path.join(outDir, file))
}

const manifest = {}

for (const entry of config) {
  const input = await readFile(path.join(root, entry.src))
  const base = () => {
    const img = sharp(input).rotate()
    if (!entry.crop) return img
    const [left, top, width, height] = entry.crop
    return img.extract({ left, top, width, height })
  }

  const meta = await base().toBuffer({ resolveWithObject: true })
  const { width, height } = meta.info
  const widths = [...new Set(entry.widths.filter((w) => w < width).concat(width))].sort((a, b) => a - b)
  const hash = createHash('sha1').update(input).update(JSON.stringify(entry)).digest('hex').slice(0, 8)

  const sources = { avif: [], webp: [] }
  for (const w of widths) {
    for (const format of ['avif', 'webp']) {
      const file = `${entry.id}-${w}.${hash}.${format}`
      const pipeline = base().resize({ width: w, withoutEnlargement: true })
      await (format === 'avif' ? pipeline.avif(AVIF) : pipeline.webp(WEBP)).toFile(path.join(outDir, file))
      sources[format].push(`images/${file} ${w}w`)
    }
  }

  // ~16px-wide blurred preview, inlined as a data URI.
  const lqip = await base().resize({ width: 16 }).webp({ quality: 45 }).toBuffer()

  manifest[entry.id] = {
    width,
    height,
    src: `images/${entry.id}-${widths.at(-1)}.${hash}.webp`,
    avif: sources.avif.join(', '),
    webp: sources.webp.join(', '),
    lqip: `data:image/webp;base64,${lqip.toString('base64')}`,
  }
  console.log(`✓ ${entry.id.padEnd(24)} ${width}×${height}  → ${widths.join(', ')}`)
}

const banner = '// AUTO-GENERATED by scripts/build-images.mjs — run `npm run images`. Do not edit by hand.\n'
const body = `export const images = ${JSON.stringify(manifest, null, 2)} as const\n\nexport type ImageId = keyof typeof images\n`
await writeFile(manifestPath, banner + body)
console.log(`\nWrote ${Object.keys(manifest).length} images to public/images and ${path.relative(root, manifestPath)}`)
