// AUTO-GENERATED by scripts/build-images.mjs — run `npm run images`. Do not edit by hand.
export const images = {
  "box-trio": {
    "width": 720,
    "height": 1278,
    "src": "images/box-trio-720.9bd91acb.webp",
    "avif": "images/box-trio-360.9bd91acb.avif 360w, images/box-trio-540.9bd91acb.avif 540w, images/box-trio-720.9bd91acb.avif 720w",
    "webp": "images/box-trio-360.9bd91acb.webp 360w, images/box-trio-540.9bd91acb.webp 540w, images/box-trio-720.9bd91acb.webp 720w",
    "lqip": "data:image/webp;base64,UklGRswAAABXRUJQVlA4IMAAAACwBACdASoQABwAPt1cqE0opSQiMAgBEBuJZgCdMoAlrw2KSi52/U4I1ngavFNAAMlXwqkDvqewe9L9VJ6DcbgmfZ2qrxlY/jeLbJ5aZKVwyik1TWuEmoHxF99LJEB4DJ+MnrcS/GY7/bucXrYzLZr9bCBsV1U28YiL/VaJE+kpguP58Yn3qrbwCFYf76RAEIlFJA4PJshZdlc+ygrVoQyAiSQCZ3O/nzVJdsz5ljlY8Y6X6lf7YImIkVeoHH4AAAA="
  },
  "plate-single": {
    "width": 720,
    "height": 1278,
    "src": "images/plate-single-720.3592194d.webp",
    "avif": "images/plate-single-360.3592194d.avif 360w, images/plate-single-540.3592194d.avif 540w, images/plate-single-720.3592194d.avif 720w",
    "webp": "images/plate-single-360.3592194d.webp 360w, images/plate-single-540.3592194d.webp 540w, images/plate-single-720.3592194d.webp 720w",
    "lqip": "data:image/webp;base64,UklGRugAAABXRUJQVlA4INwAAAAQBQCdASoQABwAPt1apkyopSOiMAgBEBuJbACdMoR3JoCYAd40nNbGIavkEiaxk8ZAAP0AwdJZN2GOp+UVZj1dXZIIzfTxKQnp9W1PXZAHWdLzyGS45PIeShjVwTSOXHBaS6GewduS4aw7ITGNaPZmPo0YowWmJ3AkkVB8yBbT4mip16YOjKBQkitB8bxEUqZ/WZPO/hCfqtKNRtCH+/a+KwsI2etoLc2NPDZs2qw3D/QQsytn0RjuQPW29737hnUy2Z9St09AZcwkPpcaMVzwLCEKUmmv+sg37AAA"
  },
  "plate-single-card": {
    "width": 720,
    "height": 900,
    "src": "images/plate-single-card-720.f1a22947.webp",
    "avif": "images/plate-single-card-360.f1a22947.avif 360w, images/plate-single-card-540.f1a22947.avif 540w, images/plate-single-card-720.f1a22947.avif 720w",
    "webp": "images/plate-single-card-360.f1a22947.webp 360w, images/plate-single-card-540.f1a22947.webp 540w, images/plate-single-card-720.f1a22947.webp 720w",
    "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAACQBACdASoQABQAPt1apkyopSOiMAgBEBuJbACdMoAlvBIBOtubZQ6o7UFVswAA/I8w8ol+zcvlSneXgwPFoEmU8PtokaVWY9mbFYgp0ivB2iT5ElnOPWcps+9vwnasFTAIuJ7ur1K5+zHSpe8GOkaT1y05UAAE5VI4bxdrQJz6+kcHvu9xsJSGoAiN6zlGdQhB0ohJQVqAMwAA"
  },
  "box-of-four-top": {
    "width": 960,
    "height": 1280,
    "src": "images/box-of-four-top-960.7b72a937.webp",
    "avif": "images/box-of-four-top-480.7b72a937.avif 480w, images/box-of-four-top-720.7b72a937.avif 720w, images/box-of-four-top-960.7b72a937.avif 960w",
    "webp": "images/box-of-four-top-480.7b72a937.webp 480w, images/box-of-four-top-720.7b72a937.webp 720w, images/box-of-four-top-960.7b72a937.webp 960w",
    "lqip": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAACQBACdASoQABUAPt1apkyopSOiMAgBEBuJZgCdIKnqQPdWd0C8tscMSyUIrAAA/dfigXUNcQDrXpCKbgU0Mt8CZ5M/ZRwYmWA2rlQvpf7k+pm7Qqc7Wc1bzyo5I3n5qnJFGAPMoqWHDAEl54JvsGDOR+agYkqv95WRYBre17lD6srApZH5sUHReoN2k1E5W3rmWgLRK1UuYha/6+XKipFnTQAAAA=="
  },
  "cheese-rolls": {
    "width": 960,
    "height": 1280,
    "src": "images/cheese-rolls-960.12767298.webp",
    "avif": "images/cheese-rolls-480.12767298.avif 480w, images/cheese-rolls-720.12767298.avif 720w, images/cheese-rolls-960.12767298.avif 960w",
    "webp": "images/cheese-rolls-480.12767298.webp 480w, images/cheese-rolls-720.12767298.webp 720w, images/cheese-rolls-960.12767298.webp 960w",
    "lqip": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAADQAwCdASoQABUAPt1apkyopSOiMAgBEBuJYwCdMoAo1gi2LNq9AwAA+TJwauof9R59TzrrixiCu2IPcQnqMhrZlza63jKem5Xx2t3M6+djTJpsUSKQAf3n30BuFPfZ5+k7hfU1a1XszbFWkaa7GjeNs5MYpzXV/TPt8l3wQNHfFrygEdpzd9GgAvfLnntAuf8XXscOUj3N1A9rrh1Bkh93pJniAAAA"
  },
  "cheese-rolls-card": {
    "width": 960,
    "height": 1200,
    "src": "images/cheese-rolls-card-960.78d3819a.webp",
    "avif": "images/cheese-rolls-card-360.78d3819a.avif 360w, images/cheese-rolls-card-540.78d3819a.avif 540w, images/cheese-rolls-card-720.78d3819a.avif 720w, images/cheese-rolls-card-960.78d3819a.avif 960w",
    "webp": "images/cheese-rolls-card-360.78d3819a.webp 360w, images/cheese-rolls-card-540.78d3819a.webp 540w, images/cheese-rolls-card-720.78d3819a.webp 720w, images/cheese-rolls-card-960.78d3819a.webp 960w",
    "lqip": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAAAwBACdASoQABQAPt1apkyopSOiMAgBEBuJYwCw7ywTngpdSkGElgluLsAA/OrHrLAvjN3PCd7ve8ky4Lsj/qnF749eL7oWTtvcR5vdEfGKPBzsJuIr8KBwcUZmuqp0jUsdyJEPdT/IAAqtpqulGSHuvPSbi0fo5YK7UbpcoCDeS63n3vZJCcQa2TSIgMXaa0rQxaET6AMucoAA"
  },
  "flavor-classic": {
    "width": 470,
    "height": 470,
    "src": "images/flavor-classic-470.d3b069c4.webp",
    "avif": "images/flavor-classic-160.d3b069c4.avif 160w, images/flavor-classic-320.d3b069c4.avif 320w, images/flavor-classic-470.d3b069c4.avif 470w",
    "webp": "images/flavor-classic-160.d3b069c4.webp 160w, images/flavor-classic-320.d3b069c4.webp 320w, images/flavor-classic-470.d3b069c4.webp 470w",
    "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAwAgCdASoQABAAAwBSJZgCdADxGbhLPzlKgAD+wb8y/O2Anr4B6tyDOst5WRIHIwCb083ZCOQnUb6ak083SUTsXmddu7dRBaFa/JV9X6eDyqvx5m/XqMTAqXu6vJ3b+THWE7bn2+3zfyBrLS8AAA=="
  },
  "flavor-cookie-crumble": {
    "width": 424,
    "height": 424,
    "src": "images/flavor-cookie-crumble-424.52170909.webp",
    "avif": "images/flavor-cookie-crumble-160.52170909.avif 160w, images/flavor-cookie-crumble-320.52170909.avif 320w, images/flavor-cookie-crumble-424.52170909.avif 424w",
    "webp": "images/flavor-cookie-crumble-160.52170909.webp 160w, images/flavor-cookie-crumble-320.52170909.webp 320w, images/flavor-cookie-crumble-424.52170909.webp 424w",
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQAgCdASoQABAAAwBSJQBOgCPwEt2F3VgAAP4f6KyTRAX0w9r+mpKuCCEADqaZvm8RGXx3VpKu59Arl9xmXuyy5necodOzrSij5QzwmWuG+/YossB/nltkVUJ8XQBLbl3zry0HPqPAAA=="
  },
  "flavor-caramel-biscuit": {
    "width": 430,
    "height": 430,
    "src": "images/flavor-caramel-biscuit-430.f46ea494.webp",
    "avif": "images/flavor-caramel-biscuit-160.f46ea494.avif 160w, images/flavor-caramel-biscuit-320.f46ea494.avif 320w, images/flavor-caramel-biscuit-430.f46ea494.avif 430w",
    "webp": "images/flavor-caramel-biscuit-160.f46ea494.webp 160w, images/flavor-caramel-biscuit-320.f46ea494.webp 320w, images/flavor-caramel-biscuit-430.f46ea494.webp 430w",
    "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAwAgCdASoQABAAAwBSJZgCdAD0t281V0YhAAD8cqCcNkYvcIW6olSWki560r0w3fOD0eAXT/tbidWUn5vV1tFx3U3Vo7ZzeMsXvjWyObta4aM5t+zJRNePgnjsPnK3rsQsE4RhyGxNNAM8FAAAAA=="
  },
  "detail-cookie-crumble": {
    "width": 480,
    "height": 384,
    "src": "images/detail-cookie-crumble-480.68cd9abd.webp",
    "avif": "images/detail-cookie-crumble-360.68cd9abd.avif 360w, images/detail-cookie-crumble-480.68cd9abd.avif 480w",
    "webp": "images/detail-cookie-crumble-360.68cd9abd.webp 360w, images/detail-cookie-crumble-480.68cd9abd.webp 480w",
    "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADwAQCdASoQAA0AAwBSJaACdADwUiUim9AA/u0koW1a0PBpnuuQKhQT7o28pt31gdKpQo1jRzFP0MMrXphDuV1Hb8I5/yfRYe0CMDGphJp0zwp6KPSW9unO3DybnkXom/LeVK6rAFrnAAAA"
  },
  "detail-caramel-biscuit": {
    "width": 470,
    "height": 376,
    "src": "images/detail-caramel-biscuit-470.34283f98.webp",
    "avif": "images/detail-caramel-biscuit-360.34283f98.avif 360w, images/detail-caramel-biscuit-470.34283f98.avif 470w",
    "webp": "images/detail-caramel-biscuit-360.34283f98.webp 360w, images/detail-caramel-biscuit-470.34283f98.webp 470w",
    "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAQAgCdASoQAA0AAwBSJbACdAD7AvuBYaoAAP7HaftyVCw0qRY6qYoy+bij+lJybr4IVF3mNv6mnjlE6LQ7qIuvHov6D2T/t6PcPQ6SqmbcEpdO1szqs4ldb+Vkfev5jBtbwr826FYHXQp/egAAAA=="
  },
  "detail-classic-swirl": {
    "width": 910,
    "height": 560,
    "src": "images/detail-classic-swirl-910.0c267675.webp",
    "avif": "images/detail-classic-swirl-480.0c267675.avif 480w, images/detail-classic-swirl-720.0c267675.avif 720w, images/detail-classic-swirl-910.0c267675.avif 910w",
    "webp": "images/detail-classic-swirl-480.0c267675.webp 480w, images/detail-classic-swirl-720.0c267675.webp 720w, images/detail-classic-swirl-910.0c267675.webp 910w",
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACQAgCdASoQAAoAAwBSJZACdAYxF2eOqDf95fADwAD2sQSnaCECp368ClKIYk3II7TzRg9jLKreeLTqLdR5kSPKJg07X8oCl3a3FmMhbAPjPtmtgAJ6X6dASuC/oT4Nkbc0EjHAAAA="
  },
  "logo-kraft-square": {
    "width": 720,
    "height": 720,
    "src": "images/logo-kraft-square-720.24c1a5a4.webp",
    "avif": "images/logo-kraft-square-360.24c1a5a4.avif 360w, images/logo-kraft-square-540.24c1a5a4.avif 540w, images/logo-kraft-square-720.24c1a5a4.avif 720w",
    "webp": "images/logo-kraft-square-360.24c1a5a4.webp 360w, images/logo-kraft-square-540.24c1a5a4.webp 540w, images/logo-kraft-square-720.24c1a5a4.webp 720w",
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAQCdASoQABAAAwBSJagCdAEJSw34AP3MYRTJEmQTZRLF5iPpp1wJmryphhHL/OlEY7W7l8jicAjv1xc3InL5N9awMjSwAAA="
  }
} as const

export type ImageId = keyof typeof images
